// Next.js 的类型：用于声明页面的 metadata（标题/描述等），Next 会自动注入到 <head>。
import type { Metadata } from "next";

// Next.js 内置的字体加载器：会在构建期下载/优化字体，并生成对应的 className/CSS 变量。
// 这里加载了 Geist Sans 和 Geist Mono 两套字体。
import { Geist, Geist_Mono } from "next/font/google";

// 引入全局样式（Tailwind 的 base/components/utilities 通常在这里挂载）
import "./globals.css";

// 配置 Sans 字体，并把它绑定到 CSS 变量 --font-geist-sans（供 Tailwind/自定义样式使用）
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// 配置等宽字体，并绑定到 CSS 变量 --font-geist-mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// App Router 的约定导出：metadata 会被 Next 自动用于 SEO/Head（不需要你手写 <Head>）
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout 是 app/ 目录下的“根布局”，会包住整个站点的所有页面。
// children 就是每个路由页面渲染出来的内容。
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html> 与 <body> 由 RootLayout 控制，适合放全局字体、主题 class、全站布局容器等
    <html
      lang="en"
      // 把字体变量挂到 html 上（geistSans.variable / geistMono.variable）
      // 后面的 h-full/antialiased 是 Tailwind 样式：全高 + 字体抗锯齿
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* body 这里做一个最小的全站 flex 列布局，页面内容从 children 注入 */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
